modLoader = "javafml"
loaderVersion = "[4,)"
license = "${license}"
issueTrackerURL = "https://github.com/nexi449/Flourish/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''${description}'''
logoFile = "flourish.png"

[[mixins]]
config = "flourish.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1, 1.21.12)"
ordering = "NONE"
side = "BOTH"